### ISSUE TITLE
Question: How to add more info below the product name?

### ISSUE THREAD

**Issue by dzunghv** [kilbot/WooCommerce-POS#181]
Hi,

I want to add more info below the product name, example: show the name of all products in the bundle http://prntscr.com/hvweod

How can I do this?
Thanks!

**Comment by ToanVenota** [comment]
Maybe try with filters: woocommerce_rest_prepare_product_object & woocommerce_rest_prepare_product_variation_object in theme functions.php by add bundles info to response array. Then modify tmpl-product.php to show this new info.

**Comment by dzunghv** [comment]
Thank you so much! 👍
