### ISSUE TITLE
How to hide the WP DASHBOARD item from Left menu

### ISSUE THREAD

**Issue by sooriyaprakasht** [kilbot/WooCommerce-POS#227]
![image](https://user-images.githubusercontent.com/59646176/73339197-36360f80-429e-11ea-8e30-31bf5c96a843.png)

I don't want to UI users to click on WP ADMIN menu and get to Woocommerce native admin page and see/change anything. I know they can still type in the direct URL site.com/wp-admin but I dont want the menu item there. Is there a way to remove the WP ADMIN Menu item alone?

Thanks

**Comment by sooriyaprakasht** [comment]
I found it after some digging. Closing. Thanks

**Comment by mirawais** [comment]
Can you please Guide how you did this. ......?
